(function() {var implementors = {};
implementors["tower_h2"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://docs.rs/h2/0.1.0/h2/error/struct.Error.html\" title=\"struct h2::error::Error\">Error</a>&gt; for <a class=\"struct\" href=\"tower_h2/client/struct.Error.html\" title=\"struct tower_h2::client::Error\">Error</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://docs.rs/h2/0.1.0/h2/frame/reason/struct.Reason.html\" title=\"struct h2::frame::reason::Reason\">Reason</a>&gt; for <a class=\"struct\" href=\"tower_h2/client/struct.Error.html\" title=\"struct tower_h2::client::Error\">Error</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://docs.rs/h2/0.1.0/h2/error/struct.Error.html\" title=\"struct h2::error::Error\">Error</a>&gt; for <a class=\"enum\" href=\"tower_h2/client/enum.HandshakeError.html\" title=\"enum tower_h2::client::HandshakeError\">HandshakeError</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"tower_h2/struct.Data.html\" title=\"struct tower_h2::Data\">Data</a>&gt; for <a class=\"struct\" href=\"https://docs.rs/bytes/0.4.6/bytes/bytes/struct.Bytes.html\" title=\"struct bytes::bytes::Bytes\">Bytes</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"tower_h2/struct.Data.html\" title=\"struct tower_h2::Data\">Data</a>&gt; for <a class=\"struct\" href=\"https://docs.rs/bytes/0.4.6/bytes/bytes/struct.BytesMut.html\" title=\"struct bytes::bytes::BytesMut\">BytesMut</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
